### ISSUE TITLE
Please release a new version for the latest change  

### ISSUE THREAD

**Issue by anellimarla** [dfabulich/sitemapgen4j#16]
Hi ! @dfabulich 

We are using gradle to pull in the library. The latest change for suffix pattern wont come up unless you publish a new release for us to use. 

Can you please do so thank you! 
Regards,
Ankita

**Comment by dfabulich** [comment]
I think I've released version 1.0.4 to Maven central. It's my first time using the new release process, so I may have made an error, but I think it'll work.
