### ISSUE TITLE
Escape XML entities

### ISSUE THREAD

**Issue by eximius313** [dfabulich/sitemapgen4j#25]
Having ```&``` in URL causes ```sitemapgen4j``` to produce invalid XML:
```
WebSitemapGenerator wsg = new WebSitemapGenerator("http://www.example.com", dir);
wsg.addUrl("http://www.example.com/Tips&Tricks.html");
wsg.write();
```
Outcome:
```
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" >
  <url>
    <loc>http://www.example.com/Tips&Tricks.html</loc>
  </url>
</urlset>
```
instead of:
```
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" >
  <url>
    <loc>http://www.example.com/Tips&amp;Tricks.html</loc>
  </url>
</urlset>
```

**Comment by eximius313** [comment]
http://www.sitemaps.org/protocol.html#escaping

**Comment by dfabulich** [comment]
Thanks for filing this. A pull request is welcome!

**Comment by eximius313** [comment]
@dfabulich any hints where should I start?
In which class would put this fix?

**Comment by dfabulich** [comment]
AbstractSitemapUrlRenderer and SitemapIndexGenerator

**Comment by eximius313** [comment]
Why there are 2 different places of writing the XML?

**Comment by dfabulich** [comment]
One of them writes a single sitemap; the other writes a sitemap index, a sitemap of sitemaps.

**Comment by eximius313** [comment]
WDYT?
https://github.com/dfabulich/sitemapgen4j/pull/26

**Comment by eximius313** [comment]
https://github.com/dfabulich/sitemapgen4j/pull/26#event-729709083

**Comment by eximius313** [comment]
@dfabulich , @mkurz could you please release new version with this fix?

**Comment by mkurz** [comment]
I just released 1.0.5 - it should be available within the next few hours.

**Comment by eximius313** [comment]
awesome!

**Comment by mkurz** [comment]
@eximius313 Thanks for the contribution.
