### ISSUE TITLE
xhtml:link support

### ISSUE THREAD

**Issue by varshneygaurav** [dfabulich/sitemapgen4j#30]
<xhtml:link rel="alternate" href="url" />

**Comment by sergiovm** [comment]
I've implemented the feature and asked for a [pull request ](https://github.com/dfabulich/sitemapgen4j/pull/33) to add it to the library.

**Comment by kiru** [comment]
Awesome. @dfabulich , is it possible to get the pull request merged? ( and maybe a release, the last one on Maven is from 2016 )

**Comment by kiru** [comment]
@dfabulich ping.

**Comment by dtrunk90** [comment]
+1

**Comment by mkurz** [comment]
Fixed via #33

**Comment by mkurz** [comment]
Version 1.1.0 with support with this feature should be available in a few hours.
