### ISSUE TITLE
sitemapgen4j as Maven dependency 

### ISSUE THREAD

**Issue by Artgit** [dfabulich/sitemapgen4j#34]
Is it possible to add sitemapgen4j as a Maven dependency ? if so, please show the example

**Comment by kiru** [comment]
What does hinder you to add it as maven dependency?
See here: https://mvnrepository.com/artifact/com.github.dfabulich/sitemapgen4j

Add the following snippet to your pom file.

<dependency>
    <groupId>com.github.dfabulich</groupId>
    <artifactId>sitemapgen4j</artifactId>
    <version>1.0.6</version>
</dependency>

**Comment by Artgit** [comment]
Thanks !
