### ISSUE TITLE
In-memory support

### ISSUE THREAD

**Issue by cnmuc** [dfabulich/sitemapgen4j#4]
Thanks for sharing this lib, saved me some time already! 
It would be great if the lib would be able to create a (file-) result without accessing the hard disk. Any plans for this feature?

**Comment by mkurz** [comment]
@cnmuc No plans right now for such a feature.
However, if you want to provide a pull request you are very welcome to do so!

**Comment by mkurz** [comment]
@cnmuc Isn't #10 what you are looking for - you can now write the Sitemap(s) into a String instead of a file. Please let us know if that's what you have been looking for.

**Comment by mkurz** [comment]
Just upgrade to version `1.0.3` and you can write the sitemaps to strings like [in this example here](https://github.com/dfabulich/sitemapgen4j/blob/master/src/test/java/com/redfin/sitemapgenerator/SitemapGeneratorTest.java#L322-L332).

**Comment by mkurz** [comment]
IMHO this if fixed by #10.
If don't agree please let us know.
