### ISSUE TITLE
Write to a Writer instead of to a file.

### ISSUE THREAD

**Issue by pedro-watermelon** [dfabulich/sitemapgen4j#40]
This allow, for example, write sitemap direct to a network connection, or gererate a in memory String with the sitemap.

**Comment by mkurz** [comment]
@pedro-watermelon If you provide a pull request I am happy to review and merge it. Thanks!

**Comment by nseb** [comment]
I'm interested too

**Comment by mkurz** [comment]
Just found out you already can write the sitemaps to a String, see #10.
However this doesn't apply to the sitemap _index_ file yet. I will fix this the coming days.

**Comment by mkurz** [comment]
Added support to write the index to a string as well: #46
Availabe in just released v1.1.2
