### ISSUE TITLE
Images in web sitemap

### ISSUE THREAD

**Issue by robertvazan** [dfabulich/sitemapgen4j#42]
Please implement image extension to sitemaps. See here:

https://support.google.com/webmasters/answer/178636

**Comment by mkurz** [comment]
@robertvazan If you provide a pull request I am happy to review and merge it.
Should be not to hard to implement this, check out #33 for example.

**Comment by robertvazan** [comment]
I am currently using this project instead:

https://github.com/jirkapinkas/jsitemapgenerator

So no pull request from me. But let's keep this issue open until someone else finds time to do it.

**Comment by mkurz** [comment]
Fixed by #45. New version 1.1.2 released.
