### ISSUE TITLE
URL using non ASCII characters [utf-8 support] 

### ISSUE THREAD

**Issue by dgosset** [dfabulich/sitemapgen4j#5]
I think this old issue still up to date
http://code.google.com/p/sitemapgen4j/issues/detail?id=16
Even the sitemp is utf-8, we can't use url with french accents like éèà etc etc

I try the fix describe in the issue and it works.
http://code.google.com/p/sitemapgen4j/issues/detail?id=16

Best regards,
Denis

**Comment by mkurz** [comment]
@dgosset Could you please provide a pull request? Thanks!

**Comment by dgosset** [comment]
done

**Comment by mkurz** [comment]
Fixed in #6

**Comment by mkurz** [comment]
@dgosset Your change has been included in todays [v1.0.3 release](https://github.com/dfabulich/sitemapgen4j/releases/tag/v1.0.3).
