### ISSUE TITLE
siteindex.xsd out of date

### ISSUE THREAD

**Issue by jiwhiz** [dfabulich/sitemapgen4j#7]
The siteindex.xsd file included is out of date. It only allows 1,000 sitemap URLs. New version from http://www.sitemaps.org/schemas/sitemap/siteindex.xsd will allow up to 50,000 sitemap URLs.

**Comment by mkurz** [comment]
@jiwhiz Thanks for reporting. Could you please provide a pull request? Thanks!

**Comment by jiwhiz** [comment]
sure. I will do that during the weekend.

**Comment by mkurz** [comment]
Thanks!
